package queueproject;

import java.util.Scanner;

public class QueueProject {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        Queue queue = new Queue(5);
        char ans;
        int number;
        int number2;
        do {
            System.out.println("what you want?");
            System.out.println("n - enqueue");
            System.out.println("d - dequeue");
            System.out.println("p - print the queue");
            System.out.println("u - update");
            System.out.println("s - search");
            System.out.println("m - show if the queue is empty");
            System.out.println("f - show if the queue is full");
            System.out.println("e - exit");
            ans = in.next().charAt(0);
            switch (ans) {
                case 'n':
                    System.out.println("enter the number you want to add");
                    number = in.nextInt();
                    queue.enqueue(number);
                    break;
                case 'd':
                    System.out.println("Removed: " + queue.dequeue());
                    break;
                case 'u':
                    System.out.println("enter the old number");
                    number = in.nextInt();
                    System.out.println("enter the new number");
                    number2 = in.nextInt();
                    queue.update(number, number2);
                    break;
                case 's':
                    System.out.println("enter the number");
                    number = in.nextInt();
                    queue.search(number);
                    break;
                case 'm':
                    System.out.println("-------------------");
                    System.out.println(queue.isEmpty());
                    System.out.println("-------------------");
                    break;
                case 'f':
                    System.out.println("-------------------");
                    System.out.println(queue.isFull());
                    System.out.println("-------------------");
                    break;
                case 'p':
                    queue.display();
                    break;
            }
        } while (ans != 'e');
    }
}
